YOLOV3:
  CFG: "./detector/YOLOv3/cfg/yolov3.cfg"
  WEIGHT: "./detector/YOLOv3/weight/yolov3_vehicle.backup"
  CLASS_NAMES: "./detector/YOLOv3/cfg/vehicles.names"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4
